version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      SA_PASSWORD: "Alaska2017"
      ACCEPT_EULA: "Y"
    expose:
      - "1433"
    ports:
      - "1433:1433"
`