CREATE DATABASE 'C:\Program Files\Firebird\Firebird_3_0\examples\people.fdb' page_size 8192;

CREATE TABLE table_first_names (id integer generated by default as identity primary key, first_name varchar(100) not null);

CREATE TABLE table_last_names (id int not null unique, last_name varchar(100) not null);

ALTER TABLE table_last_names ADD CONSTRAINT fk_fn_id foreign key (id) references table_first_names (id) using desc index index_fn_id;

insert into table_first_names (first_name) values ('Gosha');
insert into table_first_names (first_name) values ('Petya');
insert into table_first_names (first_name) values ('Ivan');
insert into table_first_names (first_name) values ('Vasya');
insert into table_first_names (first_name) values ('Fedor');

insert into table_last_names (id, last_name) values (1, 'Kucenko');
insert into table_last_names (id, last_name) values (2, 'Petrov');
insert into table_last_names (id, last_name) values (3, 'Pupkin');
insert into table_last_names (id, last_name) values (4, 'Kolokolchik');
insert into table_last_names (id, last_name) values (5, 'Emelyanenko');

commit;


